[package]
name = "vostok-codegen-impl"
version = "0.0.0"
authors = ["Zoey Riordan <zoey@dos.cafe>"]
license = "MIT OR Apache-2.0"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro-hack = "0.5"
quote = "1.0"
syn = { version = "1.0", features = ["full"] }
